//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_racing_kp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public int ID_License { get; set; }
        public string level { get; set; }
        public int ID_user { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
