//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_racing_kp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class racing_dbEntities1 : DbContext
    {
        public racing_dbEntities1()
            : base("name=racing_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Circuit> Circuit { get; set; }
        public virtual DbSet<License> License { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
