//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_racing_kp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int ID_Team { get; set; }
        public string Name { get; set; }
        public int ID_user { get; set; }
        public int ID_Circuit { get; set; }
    
        public virtual Circuit Circuit { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
