//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_racing_kp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public string link_on_picture { get; set; }
        public int ID_Team { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
